name: Rough Theory
description: An attempt to build a way.
#description: A way built by Matt Delhey.

markdown: redcarpet
highlighter: pygments
#pygments: true -- depreciated

paginate: 2
paginate_path: "/page:num"

permalink: "/posts/:title.html"

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

analytics :
  provider : google
  google : 
      tracking_id : 'UA-39546023-2'