name: Rough Theory
description: An attempt to build a way.
#description: A way built by Matt Delhey.

markdown: redcarpet
highlighter: pygments
#pygments: true -- depreciated

paginate: 2
paginate_path: "/page:num"

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']