name: rough theory
description: A way built by Matt Delhey.
#description: man is spirit. but what is spirit?

markdown: redcarpet
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']