name: Rough Theory
description: A way built by Matt Delhey.
#description: A way built by <a href='http://mattdelhey.com'>Matt Delhey</a>.
#description: man is spirit. but what is spirit?

markdown: redcarpet
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']